version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    expose:
      - "8000"
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server.key:/etc/nginx/certs/server.key
      - ./server.csr:/etc/nginx/certs/server.csr
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
